#Projects settings
project:
  config:
    SQLDBEnable: true
    SQLDBEntities: com.mokhovav.base.databases.sql

#MongoDB config

#Hibernate config
spring:
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/projectDB
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

#MongoDb config
  data:
    mongodb:
      database: base_db
      host: localhost
      port: 27017
      username: root
      password: toor
#slf4j Logger
logging:
  file:
    name: "logs/application-debug.log"
    max-size: 1MB
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"
    rolling-file-name: "logs/archived/application-debug.%d{yyyy-MM-dd}.%i.log"
  level:
    root: info
    com.mokhovav: debug