logging:
  file:
    name: "logs/application-debug.log"
    max-size: 1MB
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %C{1.} [%t] %m%n"
    rolling-file-name: "logs/archived/application-debug.%d{yyyy-MM-dd}.%i.log"

  level:
    root: error
    com.mokhovav: info



